<script setup lang="ts">
import { computed, defineAsyncComponent } from 'vue';
import { VueUiDonut, VueUiXy } from 'vue-data-ui';

// 1. 异步加载重型组件 (Univer)，避免首屏加载过慢
const UniverSheet = defineAsyncComponent({
  loader: () => import('./visualizations/UniverSheet.vue'),
  loadingComponent: {
    template: '<div class="h-[600px] w-full bg-slate-50 flex items-center justify-center text-slate-400 animate-pulse">正在加载表格引擎...</div>'
  }
});

// 2. 简单的 Markdown 渲染组件 (用于 PPT 预览)
// 实际项目中可以使用 markdown-it + slidev 样式
const SlidevPreview = defineAsyncComponent(() => import('./visualizations/SlidevPreview.vue'));

const props = defineProps<{
  uiConfig: {
    type: string;
    action: 'RENDER_UNIVER' | 'RENDER_DASHBOARD' | 'RENDER_SLIDEV' | string;
    data: any;
    message?: string;
  };
}>();

// --- Dashboard 配置生成逻辑 ---
// 为了保证 Agent 只用返回纯数据，我们在前端预设好样式配置
const dashboardConfig = computed(() => {
  const baseConfig = {
    style: {
      chart: {
        backgroundColor: "#ffffff",
        color: "#334155",
        layout: {
          labels: { dataLabels: { show: true, suffix: "%" } }
        },
        title: {
          text: props.uiConfig.data.title || "数据看板",
          color: "#1e293b",
          subtitle: { text: "Generated by AI Agent", color: "#94a3b8" }
        }
      }
    }
  };
  return baseConfig;
});

// 针对柱状图/折线图的特殊配置
const xyConfig = computed(() => ({
  ...dashboardConfig.value,
  chart: {
    padding: { top: 20, right: 20, bottom: 20, left: 20 },
    grid: { stroke: "#e2e8f0" }
  },
  bar: { borderRadius: 4, useGradient: true }
}));
</script>

<template>
  <div class="dynamic-renderer w-full mt-4 animate-fade-in border border-slate-200 rounded-xl overflow-hidden shadow-sm bg-white">
    
    <div class="bg-slate-50 px-4 py-2 border-b border-slate-100 flex justify-between items-center text-xs text-slate-500">
      <div class="flex items-center gap-2">
        <span v-if="uiConfig.action === 'RENDER_UNIVER'" class="text-green-600 font-bold bg-green-50 px-2 py-0.5 rounded">EXCEL</span>
        <span v-else-if="uiConfig.action === 'RENDER_DASHBOARD'" class="text-blue-600 font-bold bg-blue-50 px-2 py-0.5 rounded">DASHBOARD</span>
        <span v-else-if="uiConfig.action === 'RENDER_SLIDEV'" class="text-orange-600 font-bold bg-orange-50 px-2 py-0.5 rounded">PPT</span>
        <span>{{ uiConfig.data.title || 'Component' }}</span>
      </div>
      <div>{{ new Date().toLocaleTimeString() }}</div>
    </div>

    <div class="p-0">
      
      <div v-if="uiConfig.action === 'RENDER_UNIVER'" class="h-[600px] w-full">
        <UniverSheet 
          :data="uiConfig.data.snapshot" 
          :title="uiConfig.data.title" 
        />
      </div>

      <div v-else-if="uiConfig.action === 'RENDER_DASHBOARD'" class="p-6">
        <div v-if="uiConfig.data.chart_type === 'VueUiDonut'" class="max-w-lg mx-auto">
          <VueUiDonut 
            :dataset="uiConfig.data.dataset" 
            :config="dashboardConfig" 
          />
        </div>
        
        <div v-else-if="uiConfig.data.chart_type === 'VueUiXy'" class="max-w-3xl mx-auto">
          <VueUiXy 
            :dataset="uiConfig.data.dataset" 
            :config="xyConfig" 
          />
        </div>

        <div v-else class="text-center text-slate-400 py-10">
          不支持的图表类型: {{ uiConfig.data.chart_type }}
        </div>
      </div>

      <div v-else-if="uiConfig.action === 'RENDER_SLIDEV'" class="p-4 bg-slate-900 min-h-[400px]">
         <SlidevPreview 
           v-if="SlidevPreview"
           :markdown="uiConfig.data.markdown" 
         />
         <pre v-else class="text-green-400 font-mono text-sm overflow-auto p-4">{{ uiConfig.data.markdown }}</pre>
      </div>

      <div v-else class="p-8 text-center text-red-500 bg-red-50">
        Error: Unknown UI Action [{{ uiConfig.action }}]
      </div>

    </div>

    <div v-if="uiConfig.message" class="px-4 py-3 bg-slate-50 border-t border-slate-100 text-sm text-slate-600 flex gap-2 items-start">
      <span class="text-blue-500 mt-0.5">💡</span>
      <p>{{ uiConfig.message }}</p>
    </div>

  </div>
</template>

<style scoped>
.animate-fade-in {
  animation: fadeIn 0.5s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(5px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>